apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gateway
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
      - image: localhost:32000/gateway
        name: gateway
        ports:
        - containerPort: 8080
          name: gateway
---
apiVersion: v1
kind: Service
metadata:
  name: gateway
spec:
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  externalIPs:
  - 192.168.234.131
  selector:
    app: gateway
