apiVersion: apps/v1
kind: Deployment
metadata:
  name: accountservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: accountservice
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: accountservice
    spec:
      containers:
      - image: localhost:32000/accountservice
        name: accountservice
        ports:
        - containerPort: 8081
          name: accountservice
        volumeMounts:
        - name: accountservice-persistent-storage
          mountPath: /app/static/
      volumes:
      - name: accountservice-persistent-storage
        persistentVolumeClaim:
          claimName: accountservice-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: accountservice
spec:
  ports:
  - port: 8081
  selector:
    app: accountservice
