apiVersion: apps/v1
kind: Deployment
metadata:
  name: willow-db
spec:
  selector:
    matchLabels:
      app: willow-db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: willow-db
    spec:
      containers:
      - image: localhost:32000/willow_db
        name: willow-db
        ports:
        - containerPort: 3306
          name: willow-db
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
          name: mysqlback-persistent-storage
          mountPath: /docker-entrypoint-initdb.d/ 
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
        name: mysqlback-persistent-storage
        persistentVolumeClaim:
          claimName: mysqlbak-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: willow-db
spec:
  ports:
  - port: 3306
  selector:
    app: willow-db
